/* #AppInitDev -> Photo Utility Hub */



package com.t8rin.imagetoolbox.core.resources.icons

import com.t8rin.imagetoolbox.core.resources.Icons
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Icons.Outlined.FormatShapes: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "Outlined.FormatShapes",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        path(fill = SolidColor(Color.Black)) {
            moveToRelative(327f, 599f)
            lineToRelative(114f, -300f)
            quadToRelative(3f, -9f, 11f, -14f)
            reflectiveQuadToRelative(17f, -5f)
            horizontalLineToRelative(22f)
            quadToRelative(9f, 0f, 17f, 5f)
            reflectiveQuadToRelative(11f, 14f)
            lineToRelative(114f, 303f)
            quadToRelative(5f, 14f, -3f, 26f)
            reflectiveQuadToRelative(-23f, 12f)
            quadToRelative(-9f, 0f, -17f, -5.5f)
            reflectiveQuadTo(579f, 620f)
            lineToRelative(-25f, -72f)
            lineTo(408f, 548f)
            lineToRelative(-25f, 73f)
            quadToRelative(-3f, 9f, -11f, 14f)
            reflectiveQuadToRelative(-17f, 5f)
            quadToRelative(-16f, 0f, -24.5f, -13f)
            reflectiveQuadToRelative(-3.5f, -28f)
            close()
            moveTo(426f, 496f)
            horizontalLineToRelative(108f)
            lineToRelative(-52f, -150f)
            horizontalLineToRelative(-4f)
            lineToRelative(-52f, 150f)
            close()
            moveTo(40f, 880f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(80f, 680f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(-400f)
            lineTo(80f, 280f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(40f, 240f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(80f, 40f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(280f, 80f)
            verticalLineToRelative(40f)
            horizontalLineToRelative(400f)
            verticalLineToRelative(-40f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(720f, 40f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(920f, 80f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(880f, 280f)
            horizontalLineToRelative(-40f)
            verticalLineToRelative(400f)
            horizontalLineToRelative(40f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(920f, 720f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(880f, 920f)
            lineTo(720f, 920f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(680f, 880f)
            verticalLineToRelative(-40f)
            lineTo(280f, 840f)
            verticalLineToRelative(40f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(240f, 920f)
            lineTo(80f, 920f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(40f, 880f)
            close()
            moveTo(280f, 760f)
            horizontalLineToRelative(400f)
            verticalLineToRelative(-40f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(720f, 680f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(-400f)
            horizontalLineToRelative(-40f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(680f, 240f)
            verticalLineToRelative(-40f)
            lineTo(280f, 200f)
            verticalLineToRelative(40f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(240f, 280f)
            horizontalLineToRelative(-40f)
            verticalLineToRelative(400f)
            horizontalLineToRelative(40f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(280f, 720f)
            verticalLineToRelative(40f)
            close()
            moveTo(120f, 200f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveTo(760f, 200f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveTo(760f, 840f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveTo(120f, 840f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveTo(200f, 200f)
            close()
            moveTo(760f, 200f)
            close()
            moveTo(760f, 760f)
            close()
            moveTo(200f, 760f)
            close()
        }
    }.build()
}